// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-xt9D71mdFOW6KABFCLzN0IibDitZER4',
    appId: '1:472896616770:web:b5792af06eddd8fe3ff0db',
    messagingSenderId: '472896616770',
    projectId: 'news-app-32ce0',
    authDomain: 'news-app-32ce0.firebaseapp.com',
    storageBucket: 'news-app-32ce0.appspot.com',
    measurementId: 'G-YJY3QFMEXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE__XhecaAvDZRHpe5_RP-UPcADdTOiHM',
    appId: '1:472896616770:android:107da76fc68700c73ff0db',
    messagingSenderId: '472896616770',
    projectId: 'news-app-32ce0',
    storageBucket: 'news-app-32ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZW68eTXBWy5mAdH-2vhHRNHuiL8CXvas',
    appId: '1:472896616770:ios:ede751796537d3c33ff0db',
    messagingSenderId: '472896616770',
    projectId: 'news-app-32ce0',
    storageBucket: 'news-app-32ce0.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZW68eTXBWy5mAdH-2vhHRNHuiL8CXvas',
    appId: '1:472896616770:ios:ede751796537d3c33ff0db',
    messagingSenderId: '472896616770',
    projectId: 'news-app-32ce0',
    storageBucket: 'news-app-32ce0.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-xt9D71mdFOW6KABFCLzN0IibDitZER4',
    appId: '1:472896616770:web:2ea8e81711e878fe3ff0db',
    messagingSenderId: '472896616770',
    projectId: 'news-app-32ce0',
    authDomain: 'news-app-32ce0.firebaseapp.com',
    storageBucket: 'news-app-32ce0.appspot.com',
    measurementId: 'G-GR97DHWTKV',
  );
}
